# Generated by Django 6.0.2 on 2026-02-27 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('data_inicio', models.DateTimeField(verbose_name='Início do Evento')),
                ('data_fim', models.DateTimeField(verbose_name='Término do Evento')),
                ('local', models.CharField(max_length=255, verbose_name='Local/Endereço')),
                ('descricao', models.TextField(verbose_name='Descrição do Evento')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Banner/Poster')),
                ('contato_organizador', models.CharField(max_length=100, verbose_name='Contato do Organizador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Excursao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Nome do Responsável')),
                ('contato', models.CharField(max_length=20, verbose_name='WhatsApp/Telefone')),
                ('local_saida', models.CharField(max_length=255, verbose_name='Local de Embarque')),
                ('data_embarque', models.DateTimeField(verbose_name='Data/Hora Ida')),
                ('data_retorno', models.DateTimeField(verbose_name='Data/Hora Retorno')),
                ('vagas_totais', models.PositiveIntegerField(verbose_name='Total de Assentos')),
                ('vagas_ocupadas', models.PositiveIntegerField(default=0, verbose_name='Assentos Ocupados')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço da Vaga')),
                ('veiculo_tipo', models.CharField(choices=[('VAN', 'Van'), ('BUS', 'Ônibus'), ('MICRO', 'Micro-ônibus')], default='BUS', max_length=10)),
                ('veiculo_placa', models.CharField(blank=True, max_length=10, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursoes', to='core.evento')),
            ],
            options={
                'verbose_name': 'Excursão',
                'verbose_name_plural': 'Excursões',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lote', models.CharField(max_length=100, verbose_name='Tipo/Lote (Ex: Pista 1º Lote)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('quantidade_total', models.PositiveIntegerField(verbose_name='Qtd Total de Ingressos')),
                ('quantidade_vendida', models.PositiveIntegerField(default=0, verbose_name='Vendidos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Lote Ativo?')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('PAGO', 'Pago'), ('C', 'Cancelado')], default='P', max_length=10)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_participante', models.CharField(max_length=150)),
                ('cpf_participante', models.CharField(max_length=14)),
                ('email_participante', models.EmailField(max_length=254)),
                ('qr_code_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('excursao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.excursao')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lote')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido')),
            ],
        ),
    ]
