# Generated by Django 6.0.2 on 2026-03-05 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngressoGerado',
            fields=[
                ('codigo_autenticacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_participante', models.CharField(max_length=100)),
                ('cpf_participante', models.CharField(max_length=14)),
                ('rg_participante', models.CharField(max_length=20)),
                ('email_participante', models.EmailField(max_length=254)),
                ('validado', models.BooleanField(default=False)),
                ('data_uso', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.lote')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='core.pedido')),
            ],
        ),
    ]
